### PR TITLE
Optimize `parseBool`

### PR DESCRIPTION
**Pull request by SeanTheGleaming**
Instead of repeatedly calling `std.mem.eql`, this would make a single call to `ComptimeStringMap.get`

### CODE REVIEW

**Comment by MasterQ32** [comment]
I guess we should pin the CI version to 0.12 ^^ Could you do that?

**Comment by SeanTheGleaming** [comment]
Ah, looks like the name of `std.ComptimeStringMap` was just changed to `std.StaticStringMap`. I would just update the name, but I don't want to break compatibility with Zig 0.11.0 and 0.12.0, so I have an alternative implementation. Another benefit that this implementation would provide is case-insensitivity. Updating this PR in just a moment

**Comment by SeanTheGleaming** [comment]
> I guess we should pin the CI version to 0.12 ^^ Could you do that?

I'm not sure how to do that, but for now, I have an alternative implementation that shouldn't break any compatibility, and additionally is case insensitive. For the time being, we might be able to use that instead. Commiting that change in just a moment

**Comment by SeanTheGleaming** [comment]
Nevermind, figured it out, and now the CI should use 0.12.0 with this PR :)
Now it's a matter of preference between the two implementations

**Pull request merged**
